language: go

go:
  - tip

install:
  - go get -d -v ./...
  - go build -v ./...
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v github.com/mattn/goveralls

script:
  - goveralls -v -service travis-ci -repotoken K9aB4nlKTuA1IbzmOtrD2wZpnP1Aab5qs github.com/getlantern/flashlight/proxy