language: go

go:
  - tip

install:
  - go get -d -v ./...
  - go build -v ./...
  - go get code.google.com/p/go.tools/cmd/cover
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=profile.cov github.com/getlantern/flashlight/proxy
  - $HOME/gopath/bin/goveralls -v -service travis-ci -coverprofile=profile.cov -repotoken K9aB4nlKTuA1IbzmOtrD2wZpnP1Aab5qs 