language: go

go:
  - tip

install:
  - go get -d -v ./...
  - go build -v ./...
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -v -service travis-ci -repotoken K9aB4nlKTuA1IbzmOtrD2wZpnP1Aab5qs github.com/getlantern/flashlight/proxy